### ISSUE TITLE
great game, is it open source?

### ISSUE THREAD

**Issue by adbenitez** [MartinTale/monkey-bonacci#1]
my favorite entry in the mobile category so far, a pity it is so short, I won in some minutes, but I love the humor and graphics

is this open source? if so, could you please add a license file? I am interested into porting this game to [webxdc](https://webxdc.org) or if you want to make it available yourself as webxdc that would be great, there is an "app store" maintained here: https://codeberg.org/webxdc/xdcget/

**Comment by MartinTale** [comment]
Feel free to port it as long as you leave credits/links back :) Also, if you do end up doing that, do please drop me a message so I can check it out, never had anyone wanting to do something like this with one of my projects :D 

P.S. Glad you enjoyed the game <3

**Comment by adbenitez** [comment]
hi @MartinTale, your game was accepted in the store! and also your Spirit Dungeons! I didn't realized at first that you are the author of Soul Not Found, I played it time ago and liked it a lot!

![image](https://github.com/MartinTale/gibbonacci/assets/24558636/3cb063a4-155b-4eb4-ae7f-bde058c28bd5)

(note: sadly due to the sandbox restrictions, it is not possible to open links in webxdc apps, because they could be used to leak sensitive data to malicious server encoding data as part of the URL parameters etc. so I had to remove the link buttons to your discord and "buy me a coffee", if you have a better idea let me know)

if you are interested in trying out the games you need to install delta chat (you can create a temporary anonymous account scanning the QR at the end of https://webxdc.org/ if you don't want to use one of your existing email accounts)
and write me to adbenitez@hispanilandia.net and I can help you or just write to the app store bot directly, sending "hi" to xstore@testrun.org
